//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 08:55:14 PM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://danielthelux.com/soap-api/users")
package com.danielthelux.soap_api.users;
